
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://www.meshaelr.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Meshael Rahman"
title: "{ Meshael Rahman }"
description: "Personal Website of Meshael Rahman, used primarily for oppurtunities and portfolio."
keywords: "rahman, meshael, mcmaster, resume, university"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/bg1.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Meshael's favorite product is a Tesla, that acceleration and lack of torque is phenomenal!"
  - text: "Meshael can fight 14 armadillos while coding for his wedding."
  - text: "You need to be amazing like Meshael"

me-img: "/img/timeline/me.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: False
pocket-share: True
vkontakte-share: False

disqus-shortname: "MeshaelR"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/delta.png"
    date: "January 2016 - Today"
    description: "McMaster MakerSpace Head - Virtual Reality!"
  - image: "/img/timeline/samsung.jpg"
    date: "December 2014 - October 2015"
    description: "Samsung Experience Consultant"
  - image: "/img/timeline/mosaic.png"
    date: "September 2014 - October 2015"
    description: "Samsung Innovation Agent and Marketing Consultant"
  - image: "/img/timeline/youtube.png"
    date: "January 2010 - September 2015"
    description: "Founder of PixelizedChaos - Gaining 20,000 + followers"
# First image of the Timeline

timeline-img: "/img/timeline/me.jpg"

###########
# Contact #
###########

email: "MeshaelR@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Meshael is a student pursuing a degree in Engineering at McMaster University. A highly enthusiastic analytical thinker and problem solver, lover of all things electronic and mechanical."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/RahmanMeshael"
  - title: "twitter"
    url: "https://twitter.com/FindTheMesh"
  - title: "github"
    url: "https://github.com/MeshaelR"
  - title: "bitcoin"
    url: "https://blockchain.info"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
